name: food_delivery_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil:
#  pinput:
  flutter_slider_indicator: ^1.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^2.7.0
  flutter_svg: ^1.1.6
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  google_sign_in: ^6.1.4
  rename: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.0
  jiffy: ^5.0.0
  firebase_messaging: ^14.6.5
  cached_network_image: ^3.2.3
  overlay_support: ^2.1.0
  awesome_notifications: ^0.7.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/most_popular/
    - assets/images/resent_items/
    - assets/images/menu/
    - assets/images/desserts/
    - assets/icons/more/
    - assets/icons/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 700
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 500
        - asset: assets/fonts/Metropolis-Regular.otf
          weight: 400
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Metropolis-ExtraBold.otf
          weight: 800
